#  vim: set et fenc=utf-8 ff=unix sts=2 sw=2 ts=2 :
---
all:
  children:
    #------------------------------------------------------------------------#
    localhost:
      hosts:
        localhost:
          ansible_python_interpreter: "{{ playbook_dir }}/.python/bin/python"

      vars:
        ansible_connection: local
    #------------------------------------------------------------------------#
